export const FETCH_CARDS = 'FETCH_CARDS';
export const RENDER_PLAYERS = 'RENDER_PLAYERS';
export const GET_CONFIGS = 'GET_CONFIGS';
export const GET_SELECTED_CARD = 'GET_SELECTED_CARD';
export const REMOVE_SELECTED_CARD = 'REMOVE_SELECTED_CARD';
export const CHANGE_TURN_TO_START = 'CHANGE_TURN_TO_START';